<div style="background-color:#FDD5DF; padding:10px; border-radius:14px; border-left:10px solid #FF8DA1;">
<h3><b> Mid-Term Assignment - CSV to Data Warehouse </b></h3>

Introduction
fazer um indice
explicar pq escoli este dataset(maybe so no video)
explicar a junção

In [1]:
import pandas as pd

In [2]:
df_1 = pd.read_csv('tmdb_5000_movies.csv')
df_2 = pd.read_csv('tmdb_5000_credits.csv')

In [3]:
# the 'id' and 'movie_id' are the same but with different names, so we combine based on that id
df_combined = pd.merge(df_1, df_2, left_on = 'id', right_on = 'movie_id')

In [4]:
# the problem of this merge is that the df_combined will have both the 'id' and the 'movie_id', we need to remove one
df_combined.drop(columns= ['movie_id', 'title_y'], inplace = True)
df_combined.rename(columns= {'title_x' : 'title'})

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]",...,2040920,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],...,0,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...",...,0,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6,"[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],...,0,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...",...,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

**Tratar dos Missing Values**

In [5]:
df_combined.isna().sum()

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title_x                    0
vote_average               0
vote_count                 0
cast                       0
crew                       0
dtype: int64

In [6]:
df_combined = df_combined.dropna(subset=['release_date'])
df_combined = df_combined.dropna(subset=['runtime'])

In [7]:
df_combined.drop(columns = ['homepage', 'tagline', 'overview', 'keywords', 'status',], inplace = True)

In [8]:
df_combined.dtypes

budget                    int64
genres                   object
id                        int64
original_language        object
original_title           object
popularity              float64
production_companies     object
production_countries     object
release_date             object
revenue                   int64
runtime                 float64
spoken_languages         object
title_x                  object
vote_average            float64
vote_count                int64
cast                     object
crew                     object
dtype: object

In [9]:
df_combined['release_date'] = pd.to_datetime(df_combined['release_date'])
df_combined['budget'] = pd.to_numeric(df_combined['budget'], errors='coerce')
df_combined['revenue'] = pd.to_numeric(df_combined['revenue'], errors='coerce')

## **TRATAR DA COLUNA DOS GENRES**

In [10]:
fact_table = df_combined[['id','budget','revenue', 'runtime', 'popularity', 'vote_average','vote_count']]

### Dimension 1

In [48]:


dim1_date = pd.DataFrame({
    'movie_id': df_combined['id'],
    'release_date': df_combined['release_date'],
    'year': pd.to_datetime(df_combined['release_date']).dt.year,
    'month': pd.to_datetime(df_combined['release_date']).dt.month,
    'quarter': pd.to_datetime(df_combined['release_date']).dt.quarter
})

In [49]:
dim1_date

      movie_id release_date  year  month  quarter
0        19995   2009-12-10  2009     12        4
1          285   2007-05-19  2007      5        2
2       206647   2015-10-26  2015     10        4
3        49026   2012-07-16  2012      7        3
4        49529   2012-03-07  2012      3        1
...        ...          ...   ...    ...      ...
4798      9367   1992-09-04  1992      9        3
4799     72766   2011-12-26  2011     12        4
4800    231617   2013-10-13  2013     10        4
4801    126186   2012-05-03  2012      5        2
4802     25975   2005-08-05  2005      8        3

[4800 rows x 5 columns]

### Dimension 2

In [13]:
import ast

In [14]:
df_combined['genres'] = df_combined['genres'].apply(ast.literal_eval)

In [15]:
df_genres_exploded = df_combined[['id', 'genres']].explode('genres')
df_genres_exploded = df_genres_exploded.dropna(subset=['genres'])
df_genres_exploded

          id                                  genres
0      19995            {'id': 28, 'name': 'Action'}
0      19995         {'id': 12, 'name': 'Adventure'}
0      19995           {'id': 14, 'name': 'Fantasy'}
0      19995  {'id': 878, 'name': 'Science Fiction'}
1        285         {'id': 12, 'name': 'Adventure'}
...      ...                                     ...
4800  231617            {'id': 35, 'name': 'Comedy'}
4800  231617             {'id': 18, 'name': 'Drama'}
4800  231617        {'id': 10749, 'name': 'Romance'}
4800  231617       {'id': 10770, 'name': 'TV Movie'}
4802   25975       {'id': 99, 'name': 'Documentary'}

[12158 rows x 2 columns]

In [ ]:
dim_genres = pd.DataFrame({
    'movie_id': df_genres_exploded['id'],
    'genre_id': df_genres_exploded['genres'].apply(lambda x: x['id']),
    'genre_name': df_genres_exploded['genres'].apply(lambda x: x['name'])
})
dim_genres

      movie_id  genre_id       genre_name
0        19995        28           Action
0        19995        12        Adventure
0        19995        14          Fantasy
0        19995       878  Science Fiction
1          285        12        Adventure
...        ...       ...              ...
4800    231617        35           Comedy
4800    231617        18            Drama
4800    231617     10749          Romance
4800    231617     10770         TV Movie
4802     25975        99      Documentary

[12158 rows x 3 columns]

### Dimension 3 Language

**isto é pa dizer no video**

"To ensure the project remained scalable and maintainable, I implemented a dynamic mapping for the primary languages. For less frequent language codes, I used a fallback function to retain the original ISO codes, preventing data loss while keeping the ETL pipeline lean."

In [39]:
# This shows you every language code you actually have
print(df_combined['original_language'].unique())

['en' 'ja' 'fr' 'zh' 'es' 'de' 'hi' 'ru' 'ko' 'te' 'cn' 'it' 'nl' 'ta'
 'sv' 'th' 'da' 'xx' 'hu' 'cs' 'pt' 'is' 'tr' 'nb' 'af' 'pl' 'he' 'ar'
 'vi' 'ky' 'id' 'ro' 'fa' 'no' 'sl' 'ps' 'el']

In [ ]:
lang_map = {
    'en': 'English', 'ja': 'Japanese', 'fr': 'French', 'zh': 'Chinese',
    'es': 'Spanish', 'de': 'German', 'hi': 'Hindi', 'ru': 'Russian',
    'ko': 'Korean', 'cn': 'Cantonese', 'it': 'Italian', 'pt': 'Portuguese',
    'ar': 'Arabic', 'vi': 'Vietnamese', 'tr': 'Turkish', 'th': 'Thai',
    'xx': 'No Language'
}

In [38]:
dim3_language = pd.DataFrame({
    'movie_id': df_combined['id'],
    'language_code': df_combined['original_language'],
    'language_name': df_combined['original_language'].map(lang_map).fillna('Other')
})
dim3_language

      movie_id language_code language_name
0        19995            en       English
1          285            en       English
2       206647            en       English
3        49026            en       English
4        49529            en       English
...        ...           ...           ...
4798      9367            es       Spanish
4799     72766            en       English
4800    231617            en       English
4801    126186            en       English
4802     25975            en       English

[4800 rows x 3 columns]

### Dimension 4

In [ ]:
dim4_credits = df_combined[['id','cast','crew']]
dim4_credits

dim4_cast = pd.DataFrame({
    'movie_id': df_cast_exploded['id'],
    'actor_id': df_cast_exploded['cast'].apply(lambda x: x.get('id')),
    'actor_name': df_cast_exploded['cast'].apply(lambda x: x.get('name')),
    'character': df_cast_exploded['cast'].apply(lambda x: x.get('character'))
})

,id,cast,crew
0,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...
4798,9367,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,72766,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,231617,"[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,126186,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,25975,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [19]:
df_combined['cast'] = df_combined['cast'].apply(ast.literal_eval)
df_cast_exploded = df_combined[['id', 'cast']].explode('cast')
df_cast_exploded = df_cast_exploded.dropna(subset=['cast'])
df_cast_exploded

         id                                               cast
0     19995  {'cast_id': 242, 'character': 'Jake Sully', 'c...
0     19995  {'cast_id': 3, 'character': 'Neytiri', 'credit...
0     19995  {'cast_id': 25, 'character': 'Dr. Grace August...
0     19995  {'cast_id': 4, 'character': 'Col. Quaritch', '...
0     19995  {'cast_id': 5, 'character': 'Trudy Chacon', 'c...
...     ...                                                ...
4802  25975  {'cast_id': 8, 'character': 'Himself', 'credit...
4802  25975  {'cast_id': 9, 'character': 'Himself', 'credit...
4802  25975  {'cast_id': 10, 'character': 'Himself', 'credi...
4802  25975  {'cast_id': 11, 'character': 'Himself', 'credi...
4802  25975  {'cast_id': 7, 'character': 'Himself', 'credit...

[106245 rows x 2 columns]

In [30]:
gender_map = {0: 'Unknown', 1: 'Female', 2: 'Male', 3: 'Non-Binary'}

In [34]:
dim4_cast = pd.DataFrame({
    'movie_id': df_cast_exploded['id'],
    'actor_id': df_cast_exploded['cast'].apply(lambda x: x['id']),
    'actor_name': df_cast_exploded['cast'].apply(lambda x: x['name']),
    'character': df_cast_exploded['cast'].apply(lambda x: x['character']),
    'gender_label': df_cast_exploded['cast'].apply(lambda x: x.get('gender')).map(gender_map)
})

In [35]:
dim4_cast

      movie_id  actor_id          actor_name            character gender_label
0        19995     65731     Sam Worthington           Jake Sully         Male
0        19995      8691         Zoe Saldana              Neytiri       Female
0        19995     10205    Sigourney Weaver  Dr. Grace Augustine       Female
0        19995     32747        Stephen Lang        Col. Quaritch         Male
0        19995     17647  Michelle Rodriguez         Trudy Chacon       Female
...        ...       ...                 ...                  ...          ...
4802     25975     21315        Eric Roberts              Himself         Male
4802     25975      2171       Griffin Dunne              Himself      Unknown
4802     25975      2231   Samuel L. Jackson              Himself         Male
4802     25975     14407        Matt LeBlanc              Himself         Male
4802     25975    155007         Bill D'Elia              Himself         Male

[106245 rows x 5 columns]

### Dimension 5 crew

In [22]:
df_combined['crew'] = df_combined['crew'].apply(ast.literal_eval)
df_crew_exploded = df_combined[['id','crew']].explode('crew')
df_crew_exploded = df_crew_exploded.dropna(subset = ['crew'])
df_crew_exploded

         id                                               crew
0     19995  {'credit_id': '52fe48009251416c750aca23', 'dep...
0     19995  {'credit_id': '539c47ecc3a36810e3001f87', 'dep...
0     19995  {'credit_id': '54491c89c3a3680fb4001cf7', 'dep...
0     19995  {'credit_id': '54491cb70e0a267480001bd0', 'dep...
0     19995  {'credit_id': '539c4a4cc3a36810c9002101', 'dep...
...     ...                                                ...
4802  25975  {'credit_id': '58ce021b9251415a390165d9', 'dep...
4802  25975  {'credit_id': '58ce0232c3a36850e90157da', 'dep...
4802  25975  {'credit_id': '52fe44e8c3a368484e03da8d', 'dep...
4802  25975  {'credit_id': '52fe44e8c3a368484e03da87', 'dep...
4802  25975  {'credit_id': '52fe44e8c3a368484e03da97', 'dep...

[129574 rows x 2 columns]

** We choose to only keep the directors because that is the more valuable information. we ususally dont need to know whos the colourist but we need to know the director** 


**data warehousing is about choosing what we really need, this way we reduced the number of rows from 197.000 to just 5000**

In [23]:
df_directors = df_crew_exploded[df_crew_exploded['crew'].apply(lambda x: x['job'] == 'Director')]

In [33]:
dim5_crew = pd.DataFrame({
    'movie_id': df_directors['id'],
    'director_id': df_directors['crew'].apply(lambda x: x['id']),
    'director_name': df_directors['crew'].apply(lambda x: x['name']),
    'job': 'Director', # Optional: good for showing what the role is
    'gender_label' : df_directors['crew'].apply(lambda x: x.get('gender')).map(gender_map)
})


dim5_crew

      movie_id  director_id      director_name       job gender_label
0        19995         2710      James Cameron  Director         Male
1          285         1704     Gore Verbinski  Director         Male
2       206647           39         Sam Mendes  Director         Male
3        49026          525  Christopher Nolan  Director         Male
4        49529            7     Andrew Stanton  Director         Male
...        ...          ...                ...       ...          ...
4800    231617      1219158        Scott Smith  Director      Unknown
4801    126186       208138        Daniel Hsia  Director         Male
4802     25975        85563   Brian Herzlinger  Director         Male
4802     25975        94471           Jon Gunn  Director         Male
4802     25975       997560         Brett Winn  Director      Unknown

[5164 rows x 5 columns]

In [29]:
print(df_cast_exploded['cast'].iloc[3])

{'cast_id': 4, 'character': 'Col. Quaritch', 'credit_id': '52fe48009251416c750ac9cf', 'gender': 2, 'id': 32747, 'name': 'Stephen Lang', 'order': 3}